### ISSUE TITLE
404 not found after installation on Magento 1.9.2.2

### ISSUE THREAD

**Issue by srinath461** [astorm/PulsestormLauncher#4]
I have installed the plugin on my site but it shows 404 error. How should i resolve it ? Thanks.
![drstore-errorimage](https://cloud.githubusercontent.com/assets/5940674/15500024/8a51b3a2-21c4-11e6-90d2-b8d8417aeda1.PNG)

**Comment by astorm** [comment]
@srinath461 Thanks for using my extension.  The error you're seeing looks like a cached super user ACL credentials.  Logging out and logging in is usually enough to clear it.  If that doesn't work, you'll need to clear your admin session cookie and/or PHP session file.  This is a long standing, known issue in Magento 1 with no clear solution.

**Comment by srinath461** [comment]
@astorm  Thank you for the feedback. I will try your suggestion.
